/*
    resource.h
*/

#ifndef _RESOURCE_H_
#define _RESOURCE_H_

#define IDR_JSON_MANIFEST_GOOGLE 10
#define IDR_JSON_MANIFEST_MOZILLA 11

#define IDS_APP_HOST_NAME 100

#define IDS_NATIVE_MESSAGING_GOOGLE_HOSTS_PATH 101
#define IDS_REGISTER_GOOGLE_INFO 102

#define IDS_NATIVE_MESSAGING_MOZILLA_HOSTS_PATH 103
#define IDS_REGISTER_MOZILLA_INFO 104

#endif // _RESOURCE_H_
